password_mismatch = "Error for password mismatch not shown"
continue_button_visible = "Continue button is visible"
password_setup_failed = "Failed creating new password"
reset_drive_with_invalid_PSID = "Reset drive allowed Invalid PSID"
lock_drive_invalid_pass = "Drive locked with invalid password"
unlock_drive_invalid_pass = "Drive unlocked with an invalid password"
lock_drive_failed       = "Locking drive failed with a valid password"
failed_changing_password = "Failed changing password..."
crypto_erase_with_invalid_pass = "Crypto erase successful with invalid password"
crypto_erase_failed = "Crypto erase failed..."
disable_sec_with_invalid_pass = "Disabling security successful with invalid password"
disable_security_failed = "Disabling security failed..."
enable_sec_with_invalid_pass = "Enabling security successful with invalid password"
enable_security_failed = "Enabling security failed..."
help_page_not_open = "Failed opening Seagate Secure help page.."
storage_screen_deet_not_visible = "Storage screen is not visible"
os_screen_deet_not_visible = "OS screen not visible"
done_screen_deet_not_visible = "Done screen not visible"
optimize_screen_not_visible = "Optimize card not visible"
toolkit_main_screen_not_visible = "Toolkit main screen not visible"
content_synced = "Expected content synced on the drive"
content_sync_failed = "Expected content failed syncing on the drive."


