#suite_name      = 'Lyve Pilot SC smoke'
#suite_desc      = "Lyve Pilot SC Test Suite"
testrail_user   = "tammy.ngo@seagate.com"
testrail_pass   = "qa123"
shared_folder   = "Shared"
build_version   = "1.8"
project_id      =20
master_suite_id =0
usb_hub_port    = 0
drive_name      = "AutoTest"
#report_name     = "Lyve_Pilot_SC_Tests_Report"

installer_type  = "Lacie"
feed_url        = "https://s3-us-west-2.amazonaws.com/csg-app-updates/omni/win/auto/update_win_0820.ini"
#locale_path     = "/Users/qa/Library/Application Support/Toolkit/PlugIns/Security.omniplugin/Contents/Resources/" + lang + ".lproj/" + "Localizable.strings"
#test_info       ={'Lyve_Pilot_SC_Accelerator_Smoke_Tests': []}
test_info       ={'op_smoke': []}
test_order      =['op_smoke']
#test_order      =['Lyve_Pilot_SC_Accelerator_Smoke_Tests']
#suite_name      = 'Lyve_Pilot_SC_Accelerator_Smoke_Tests'
suite_name      = 'Optimus smoke'
suite_desc      = "Optimus Test Suite"
report_name     = "Optimus_Suite_Tests_Report"
report_title    = suite_name + "_tests"
#run_name        = "Lyve_Pilot_SC_Accelerator_Smoke_Tests"

userName        = "tammyngo"
jiraServer      = "https://jira.corp.lyveminds.com/"
jiraUserName    = "tammy.ngo"
jiraPassword    = "ngo8748"
device_list     = ["LaCie Rugged RAID Shuttle", "Backup Plus Ultra Touch"]
source_drive_name    = "LaCie"
dest_drive_name     = "Seagate"
home_folder     = "qa"
suites_path     = "../suites/"
user_email      = "tammy.ngo@seagate.com"
send_email_to   = ['tammy.ngo@seagate.com']
email_title     = "Report Lyve Pilot SC"
platform        = "Windows"
OS              = "Windows 10"
app_name        = "Lyve Pilot SC"
build_num       = "latest"
version         = "1.0"
lang            = "en"
release_name    = "Accelerator"
test_plan_name  = app_name + " Test Plan for " + release_name
test_set_name   = suite_name
test_exec_name  = "Auto Execution of {}".format(suite_name)
locale_path     = "/Users/qa/Library/Application Support/Toolkit/PlugIns/Security.omniplugin/Contents/Resources/" + lang + ".lproj/" + "Localizable.strings"
features_file_path = "../configs/danni_features.txt"
