test_info       ={'op_smoke': []}
test_order      =['op_smoke']
suite_name      = 'Lyve Client smoke for windows v.1.99.17'
suite_desc      = "Lyve Client windows Test Suite"
userName        = "534026"
testrail_user   = "tammy.ngo@seagate.com"
testrail_pass   = "qa123"
home_folder     = "qa"
jiraServer      = "https://jira.corp.lyveminds.com/"
jiraUserName    = "534026"
jiraPassword    = "ngo8748"
shared_folder   = "Shared"
app_name        = "Lyve Client"
release_name    = "Accelerator"

test_plan_name  = app_name + " Test Plan for  windows " + release_name
test_set_name   = suite_name
test_exec_name  = "Auto Execution of {}".format(suite_name)
OS              = "Windows 10"
device_list     = ["LaCie Rugged RAID Pro Drive", "DJI Fly Drive, LaCie Rugged SSD"]
build_version   = "1.8"
project_id      =20
master_suite_id =0
usb_hub_port    = 0
drive_name      = "AutoTest"
report_name     = "Lyve_Client_Suite_Tests_Report"
suites_path     = "..\\suites\\optimus_suites\\"
user_email      = "tammy.ngo@seagate.com"
send_email_to   = ["tammy.ngo@seagate.com"]
email_title     = "Test report for Lyve Client windows Test Suite"
report_title    = suite_name + "_tests"
platform        = "Windows 10"
lang            = "en"
installer_type  = "LaCie"
